# environment.yml
name: data_science_ollama
channels:
  - conda-forge

dependencies:
  # Core Conda dependencies
  - python=3.10
  - libxml2
  - libarchive
  - pip<24.1
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pytest
  - black
  - flake8
  - mypy
  - faiss-gpu
  - PySide6
  - pyaudio
  - python-dotenv
  - networkx
  - spacy
  - tqdm
  - pydantic
  - pip:
      - pretty_errors
      - nltk
      - rank_bm25
      - langchain
      - langchain_community
      - langchain_chroma
      - langchain-ollama
      - langchain-experimental
      - langchain-anthropic
      - langchain-nomic
      - langchainhub
      - langsmith
      - langgraph
      - tavily-python
      - nba_api
      - sentencepiece
      - duckdb
      - plotly-express
      - tiktoken
      - streamlit>=1.0.0
      - langserve
      - sqlalchemy
      - transformers>=4.31.0
      - huggingface_hub>=0.10.0
      - accelerate>=0.19.0
      - torch>=2.0.0
      - sentence-transformers>=2.2.2
      - bitsandbytes
      - neo4j
      - llama_index
      - litellm
      - phi
      - py2neo
      - litserve
      - PyPDF2
      - flask
